### ISSUE TITLE
AsyncQue not running

### ISSUE THREAD

**Issue by kaspar-allenbach** [ostark/craft-async-queue#21]
I've installed AsyncQueue localy on MAMP and it is not runing.

But when I deactivate the plugin and then activate it again it runs smoothly. Why?

Craft CMS 3.1.28
AsyncQueue 2.0.0
PHP 7.2.14
Apache

No Errors in the queue.log

**Comment by theskyfloor** [comment]
Having similar issues on a forge server... any ideas?

**Comment by yiska** [comment]
We are also seeing an issue after upgrading to 2.0.0. Our tasks are not running any longer. I suspect it has to do with some change that was made to decouple QueueCommand form QueueHandler but I have not spent enough time digging through that. When I manually downgrade back to 1.4.0, the queue operates as it should with the latest version of Craft.

**Comment by superflausch** [comment]
We see the same behaviour on our server. Worked just fine, then stopped. Not able to see anything in our logs. Disabling and enabling again resolves this.

**Comment by ostark** [comment]
@superflausch please provide more details

* Software versions?
* Worked just fine, then stopped??
* console.log & queue.log are empty?
* jobs table is full?

**Comment by superflausch** [comment]
Sure, I guess I was a little quick. Since the disabling/enabling it seems to work just fine. I will observe and report if I see the same behaviour again.

I noticed the stalled tasks today (slug updates, template cache), which worked just fine a couple of days ago. Cleared the jobs table. Ran the Async Queue Test, those tasks also got stuck. Empty console.log and queue.log.

PHP 7.3.12
MySQL 5.5.5
Craft Pro 3.4.0-beta.4
AsyncQueue 2.0.0
Apache

**Comment by ostark** [comment]
Please give 2.1 a try https://github.com/ostark/craft-async-queue/commit/f53f835f446afa7dbb5af8d42b0482ba3fbafbce

**Comment by espensgr** [comment]
This is still an issue with the latest version. And i have never been able to run this on mye local MAMP, it just doesn't run, even if i run the nice command from the settings in my terminal.

**Comment by internetztube** [comment]
Same issue here.

**Comment by tsawitzki** [comment]
+1, exactly the same issue here
