### ISSUE TITLE
Moved a client's site to Commerce 3 and emails not sending

### ISSUE THREAD

**Issue by joneslafuente** [ostark/craft-async-queue#64]
Hi, successfully updated a client's site to Craft 3/Commerce 3 and all is good apart from order emails not being sent. I have read various threads and came across your plugin. Installed and was hoping all would be working but no. now we see the queue and is stuck on pending. Never gets pas this stage. Is there something else I need to be doing?

I am not a developer so the plugin route for me was the best option.

Using Craft 3.7.57 and Commerce 3.4.17.2. Is AsyncQueue 2.3.0 the latest that can be installed? That is all I see in the plugin store.

Many thanks

Brian

**Comment by jmauzyk** [comment]
@ostark We're running into this as well. Do you have any suggestions for troubleshooting to try and resolve this issue?

**Comment by ostark** [comment]
Did it work before?

Check your console.log and queue.log

**Comment by jmauzyk** [comment]
It worked prior to Commerce 3 and 4. No warnings or errors to speak of in either console.log or queue.log.

**Comment by jmauzyk** [comment]
I looked into this a bit more and think I figured out a resolution. For us, this issue was only happening on order completion when our order confirmation email is supposed to be sent. After digging into what was happening in the queue, it seemed like there weren't enough queue runners and they were getting overwhelmed by several *Updating search indexes* jobs that are queued on or around order completion.

Updating the `ASYNC_QUEUE_CONCURRENCY` setting to 5 seems to have resolved the issue so far.
